### ISSUE TITLE
`-q` and `--quality` flags on `cjpegli` are ignored

### ISSUE THREAD

**Issue by Ampflower** [google/jpegli#29]
**Describe the bug**
`cjpegli`'s quality flag doesn't use the equivalent distance like `cjxl` does, instead using the distance of 1 regardless of input.

**To Reproduce**
1. Have any PNG to convert.
2. Build jpegli
3. Run `cjpegli input.png output.jpg -q 70`

**Expected behavior**
For the distance to be roughly 2.5, rather than 1.

**Screenshots**
Images inapplicable as it is a logic problem. Instead, a log:
```
$ ./cjpegli input.png output.jpg -q 70 -v -v
Read 1920x1080 image, 1856814 bytes.
Encoding [YUV d1.000 AQ p2 OPT]
Compressed to 203130 bytes (0.784 bpp).
1920 x 1080,  40.560 MP/s [40.56, 40.56], , 1 reps, 1 threads.
```

**Environment**
 - OS: Arch Linux
 - Compiler version:
   - The C compiler identification is GNU 14.2.1
   - The CXX compiler identification is GNU 14.2.1
   - gcc (GCC) 14.2.1 20240805 // via Arch Linux
 - CPU type: x86_64
 - cjxl/djxl version string: N/A; commit: be525a452e8b989de886118f049ab1440870e447

**Additional context**
Happens regardless of any input. However, the `-d` flag works as expected, with changes in the log corresponding.

```
$ ./cjpegli input.png output.jpg -d 3 -v -v
Read 1920x1080 image, 1856814 bytes.
Encoding [YUV d3.000 AQ p2 OPT]
Compressed to 195866 bytes (0.756 bpp).
1920 x 1080,  40.999 MP/s [41.00, 41.00], , 1 reps, 1 threads.
```

**Comment by pegleGrot** [comment]
I don't think the `"d1.000"` output there really means it's the same as `-d 1`.
If you try different `-q ##` values the output size will be different, I presume.
